kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: geth-pv-claim
spec:
  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.data.volumeSize }}
